import os
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from core.schemas import FinalAssessment

def generate_pdf(assessment: FinalAssessment, output_path: str):
    """
    Generates a professional PDF report from the FinalAssessment data.
    """
    doc = SimpleDocTemplate(output_path, pagesize=letter)
    styles = getSampleStyleSheet()
    Story = []

    # Title
    title_style = styles['Heading1']
    Story.append(Paragraph(f"Cognitive Assessment Report - Patient: {assessment.patient_id}", title_style))
    Story.append(Spacer(1, 12))

    # Overall Risk
    risk_style = ParagraphStyle(
        'RiskStyle',
        parent=styles['Heading2'],
        textColor='red' if assessment.risk_level == "High Risk" else 'green' if assessment.risk_level == "Low Risk" else 'orange'
    )
    Story.append(Paragraph(f"Overall Cognitive Score: {assessment.overall_score:.2f}%", styles['Heading2']))
    Story.append(Paragraph(f"Risk Classification: {assessment.risk_level}", risk_style))
    Story.append(Spacer(1, 24))

    # Speech Metrics
    Story.append(Paragraph("1. Speech & Language Analysis", styles['Heading3']))
    speech_text = f"""
    Total Words: {assessment.speech.total_words}<br/>
    Vocabulary Richness: {assessment.speech.vocabulary_richness:.2f}<br/>
    Speech Rate (WPM): {assessment.speech.speech_rate_wpm:.2f}
    """
    Story.append(Paragraph(speech_text, styles['Normal']))
    Story.append(Spacer(1, 12))

    # Memory Metrics
    Story.append(Paragraph("2. Memory Assessment", styles['Heading3']))
    memory_text = f"""
    Immediate Recall Score: {assessment.memory.immediate_score:.2f}%<br/>
    Delayed Recall Score: {assessment.memory.delayed_score:.2f}%<br/>
    Assigned Words: {', '.join(assessment.memory.words_assigned)}
    """
    Story.append(Paragraph(memory_text, styles['Normal']))
    Story.append(Spacer(1, 12))

    # Attention & Language
    Story.append(Paragraph("3. Attention & Executive Function", styles['Heading3']))
    attn_text = f"""
    Digit Span Score: {assessment.attention.total_score:.2f}%<br/>
    Verbal Fluency Score: {assessment.fluency.score:.2f}%<br/>
    Naming Score: {assessment.naming.score:.2f}%
    """
    Story.append(Paragraph(attn_text, styles['Normal']))
    Story.append(Spacer(1, 24))
    
    # Disclaimer
    disclaimer_style = ParagraphStyle('Disclaimer', parent=styles['Italic'], fontSize=8)
    Story.append(Paragraph("Disclaimer: This report is generated by SilentCare AI for screening purposes only. It is not a clinical diagnosis. Please consult a qualified medical professional for interpretation.", disclaimer_style))

    doc.build(Story)
